export { default as IntroBanner } from './IntroBanner'
export { default as FeatureSlice } from './FeatureSlice'
export { default as PriceSlice } from './PriceSlice'
export { default as ImagesSlice } from './ImagesSlice'
export { default as ColumnImageSlice } from './ColumnImageSlice'